### ISSUE TITLE
Running any Command in 1.20.4 crashes the server

### ISSUE THREAD

**Issue by ApplecakeYT** [FlashyReese/CommandAliases#60]
When updated from 1.19.4 -> 1.20.4, tested with a single command `readycheck.json` containing...
```json
{
	"schemaVersion": 1,
	"commandMode": "COMMAND_CUSTOM",
	"command": "readycheck",
	"permission": 1,
    "actions": [
        {
            "command": "function server:actions/readycheck/init",
            "commandType": "CLIENT"

        }
       ]
}
```
Crashed the server, here is the crash report [redacted some bits]

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-02-27 16:09:02
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_2585
	at eu.pb4.placeholders.impl.GeneralUtils.convertToNodes(GeneralUtils.java:239)
	at eu.pb4.placeholders.api.node.TextNode.convert(TextNode.java:29)
	at eu.pb4.placeholders.api.Placeholders.parseText(Placeholders.java:124)
	at me.flashyreese.mods.commandaliases.command.builder.custom.ServerCustomCommandBuilder.formatString(ServerCustomCommandBuilder.java:38)
	at me.flashyreese.mods.commandaliases.command.builder.custom.AbstractCustomCommandBuilder.lambda$scheduleAction$6(AbstractCustomCommandBuilder.java:317)
	at me.flashyreese.mods.commandaliases.command.Scheduler.processEvents(Scheduler.java:26)
	at me.flashyreese.mods.commandaliases.command.loader.CommandAliasesLoader.lambda$registerCommandAliases$3(CommandAliasesLoader.java:95)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$bkn000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:4934)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:874)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2585
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 5.15.0-53-generic
	Java Version: 17.0.7, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2392225280 bytes (2281 MiB) / 6593445888 bytes (6288 MiB) up to 8606711808 bytes (8208 MiB)
	CPUs: 2
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Virtual memory max (MB): 64372.41
	Virtual memory used (MB): 56981.99
Fabric Mods: 
		commandaliases: Command Aliases 1.0.1+mc1.20-build.68
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-toml: jackson-dataformat-toml 2.15.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.15.2
			com_fathzer_javaluator: javaluator 3.0.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mysql_mysql-connector-java: mysql-connector-java 8.0.29
			org_apache_commons_commons-pool2: commons-pool2 2.11.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_yaml_snakeyaml: snakeyaml 2.0
			placeholder-api: Placeholder API 2.1.1+1.20
			redis_clients_jedis: jedis 4.2.3
			Server Running: true
	Player Count: 1 / 10000; [class_3222['Applecake_'/11, l='ServerLevel[Blank World]', x=254.83, y=129.00, z=285.70]]
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```
Here is server output when the crash occurred.
```
[16:19:17] [Server thread/INFO]: 
commandaliases
└── readycheck.json - Successfully loaded
[16:19:17] [Server thread/INFO]: Registered/Reloaded all your commands :P, you can now single command nuke!
[16:19:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_2585
        at eu.pb4.placeholders.impl.GeneralUtils.convertToNodes(GeneralUtils.java:239) ~[placeholder-api-2.1.1+1.20-6fd529212152a823.jar:?]
        at eu.pb4.placeholders.api.node.TextNode.convert(TextNode.java:29) ~[placeholder-api-2.1.1+1.20-6fd529212152a823.jar:?]
        at eu.pb4.placeholders.api.Placeholders.parseText(Placeholders.java:124) ~[placeholder-api-2.1.1+1.20-6fd529212152a823.jar:?]
        at me.flashyreese.mods.commandaliases.command.builder.custom.ServerCustomCommandBuilder.formatString(ServerCustomCommandBuilder.java:38) ~[commandaliases-1.0.1+mc1.20-build.68.jar:?]
        at me.flashyreese.mods.commandaliases.command.builder.custom.AbstractCustomCommandBuilder.lambda$scheduleAction$6(AbstractCustomCommandBuilder.java:317) ~[commandaliases-1.0.1+mc1.20-build.68.jar:?]
        at me.flashyreese.mods.commandaliases.command.Scheduler.processEvents(Scheduler.java:26) ~[commandaliases-1.0.1+mc1.20-build.68.jar:?]
        at me.flashyreese.mods.commandaliases.command.loader.CommandAliasesLoader.lambda$registerCommandAliases$3(CommandAliasesLoader.java:95) ~[commandaliases-1.0.1+mc1.20-build.68.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.3+78d798af4f-6bde62e1763006d1.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bkn000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:4934) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:874) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2585
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
```
